eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:    
      # defaultZone: http://localhost:8761/eureka/
      defaultZone: http://192.168.0.108:8080/service-registery/eureka
  # instance:
  #     hostname: localhost
  instance:
    hostname: 192.168.0.108
    prefer-ip-address: true
